In [1]:
import pandas as pd

### 数据分组计算

In [2]:
# 按照一列分组统计
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')
# print(df)

print('========------------=============------------============--------')
df1 = df[['产品名称', '数量', '标准单价']]
# print(df1)
print(df1.groupby('产品名称', as_index=False).sum())   #  对数量， 标准单价 都进行求和统计
print('========------------=============------------============--------')
print(df1.groupby('产品名称').sum())   # as_index=False 默认为True，表示保留原来的列名

========------------=============------------============--------
     产品名称  数量  标准单价
0     DVD光驱   150       960
1    SD存储卡    44       870
2      手写板    57       380
3    无线网卡    40       356
4  蓝牙适配器   322       648
5        键盘   140       360
6      麦克风   178       495
7        鼠标   166      1495
========------------=============------------============--------
            数量  标准单价
产品名称
DVD光驱      150       960
SD存储卡      44       870
手写板        57       380
无线网卡      40       356
蓝牙适配器   322       648
键盘         140       360
麦克风       178       495
鼠标         166      1495

In [3]:
# 按照多列分组统计
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')

df2 = df[['产品名称', '销售员', '数量']]
df3 = df2.groupby(['产品名称','销售员']).sum()    # 对数量进行求和

print(df3)

                   数量
产品名称   销售员
DVD光驱    华国华    88
           王丽      62
SD存储卡   李桂林    35
           李欢       9
手写板     华国华    14
           王丽      43
无线网卡   李桂林    30
           王丽      10
蓝牙适配器 李桂林   176
           李欢      95
           王丽      51
键盘       华国华    20
           王丽     120
麦克风     华国华    47
           李桂林    55
           李欢      62
           王丽      14
鼠标       李桂林    93
           李欢      21
           王双      52

In [4]:
# 分组并按指定列进行计算
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')

df1 = df[['产品名称', '数量', '标准单价']]
print(df1.groupby('产品名称')['数量'].sum())

产品名称
DVD光驱       150
SD存储卡       44
手写板         57
无线网卡       40
蓝牙适配器    322
键盘          140
麦克风        178
鼠标          166
Name: 数量, dtype: int64

###  分组数据迭代

In [5]:
# 分组数据迭代
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')

df1 = df[['产品名称', '数量', '标准单价']]    # 选取需要的列
# print(df1.groupby('产品名称'))

for name, group in df1.groupby('产品名称'):
    print(name)
    print(group)
    print('***************************')

DVD光驱
   产品名称  数量  标准单价
25  DVD光驱    30       240
26  DVD光驱    32       240
27  DVD光驱    40       240
28  DVD光驱    48       240
***************************
SD存储卡
    产品名称  数量  标准单价
22  SD存储卡     9       290
23  SD存储卡    15       290
24  SD存储卡    20       290
***************************
手写板
  产品名称  数量  标准单价
7   手写板    14       190
8   手写板    43       190
***************************
无线网卡
   产品名称  数量  标准单价
0  无线网卡    10       178
1  无线网卡    30       178
***************************
蓝牙适配器
      产品名称  数量  标准单价
14  蓝牙适配器    18       108
15  蓝牙适配器    39       108
16  蓝牙适配器    51       108
17  蓝牙适配器    58       108
18  蓝牙适配器    61       108
19  蓝牙适配器    95       108
***************************
键盘
   产品名称  数量  标准单价
20     键盘    20       180
21     键盘   120       180
***************************
麦克风
   产品名称  数量  标准单价
9    麦克风     4        99
10   麦克风    10        99
11   麦克风    47        99
12   麦克风    55        99
13   麦克风    62        99
***************************
鼠标
  产品名称  数量  标准单价
2     鼠标     6       299
3     鼠标    15       299
4     鼠标    16       299
5     鼠标    52       299
6     鼠标    77       299
***************************

In [6]:
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')

df2 = df[['产品名称', '销售员', '数量']]

print(df3)
for (k1, k2), group in df2.groupby(['产品名称','销售员']):
    print(k1, k2)
    print(group)
    print()

                   数量
产品名称   销售员
DVD光驱    华国华    88
           王丽      62
SD存储卡   李桂林    35
           李欢       9
手写板     华国华    14
           王丽      43
无线网卡   李桂林    30
           王丽      10
蓝牙适配器 李桂林   176
           李欢      95
           王丽      51
键盘       华国华    20
           王丽     120
麦克风     华国华    47
           李桂林    55
           李欢      62
           王丽      14
鼠标       李桂林    93
           李欢      21
           王双      52
DVD光驱 华国华
   产品名称  销售员  数量
27  DVD光驱  华国华    40
28  DVD光驱  华国华    48

DVD光驱 王丽
   产品名称 销售员  数量
25  DVD光驱   王丽    30
26  DVD光驱   王丽    32

SD存储卡 李桂林
    产品名称  销售员  数量
23  SD存储卡  李桂林    15
24  SD存储卡  李桂林    20

SD存储卡 李欢
    产品名称 销售员  数量
22  SD存储卡   李欢     9

手写板 华国华
  产品名称  销售员  数量
7   手写板  华国华    14

手写板 王丽
  产品名称 销售员  数量
8   手写板   王丽    43

无线网卡 李桂林
   产品名称  销售员  数量
1  无线网卡  李桂林    30

无线网卡 王丽
   产品名称 销售员  数量
0  无线网卡   王丽    10

蓝牙适配器 李桂林
      产品名称  销售员  数量
14  蓝牙适配器  李桂林    18
15  蓝牙适配器  李桂林    39
17  蓝牙适配器  李桂林    58
18  蓝牙适配器  李桂林    61

蓝牙适配器 李欢
      产品名称 销售员  数量
19  蓝牙适配器   李欢    95

蓝牙适配器 王丽
      产品名称 销售员  数量
16  蓝牙适配器   王丽    51

键盘 华国华
   产品名称  销售员  数量
20     键盘  华国华    20

键盘 王丽
   产品名称 销售员  数量
21     键盘   王丽   120

麦克风 华国华
   产品名称  销售员  数量
11   麦克风  华国华    47

麦克风 李桂林
   产品名称  销售员  数量
12   麦克风  李桂林    55

麦克风 李欢
   产品名称 销售员  数量
13   麦克风   李欢    62

麦克风 王丽
   产品名称 销售员  数量
9    麦克风   王丽     4
10   麦克风   王丽    10

鼠标 李桂林
  产品名称  销售员  数量
4     鼠标  李桂林    16
6     鼠标  李桂林    77

鼠标 李欢
  产品名称 销售员  数量
2     鼠标   李欢     6
3     鼠标   李欢    15

鼠标 王双
  产品名称 销售员  数量
5     鼠标   王双    52

### 对一列或多列使用聚合函数

In [7]:
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)
df = pd.read_excel('data/电脑配件销售记录.xlsx')
# print(df.head())

df1 = df[['产品名称', '数量']]
# print(df1)
print(df1.groupby('产品名称').agg(['sum', 'mean', 'max', 'min']))

           数量
            sum       mean  max min
产品名称
DVD光驱     150  37.500000   48  30
SD存储卡     44  14.666667   20   9
手写板       57  28.500000   43  14
无线网卡     40  20.000000   30  10
蓝牙适配器  322  53.666667   95  18
键盘        140  70.000000  120  20
麦克风      178  35.600000   62   4
鼠标        166  33.200000   77   6

In [8]:
# 对不同的列采用不同的聚合函数
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)

df = pd.read_excel('data/电脑配件销售记录.xlsx')

df1 = df[['产品名称', '数量', '成交金额']]
df1.groupby('产品名称').agg({'数量':['sum', 'mean'], '成交金额':['max', 'min']})

           数量            成交金额
            sum       mean      max   min
产品名称
DVD光驱     150  37.500000    11520  7200
SD存储卡     44  14.666667     5800  2610
手写板       57  28.500000     8170  2660
无线网卡     40  20.000000     5340  1780
蓝牙适配器  322  53.666667    10260  1944
键盘        140  70.000000    21600  3600
麦克风      178  35.600000     6138   396
鼠标        166  33.200000    23023  1794

### 通过自定义函数实现分组统计

In [9]:
import pandas as pd
pd.set_option('display.unicode.east_asian_width', True)

df = pd.read_excel('data/电脑配件销售记录.xlsx')


print(type(df['产品名称']))  # <class 'pandas.core.series.Series'>
# print(df['产品名称'].value_counts())  # 产品名称的最多的个数  

max_count = lambda x: x.value_counts().index[0]    # 行索引为0的
# max_count 是一个匿名函数，它接受一个 Series（在这里是 '产品名称' 列），
# 使用 value_counts() 统计元素出现的频率，然后取频率最高的元素（即 index[0]）。

max_count.__name__='销量个数最多的产品'

df1= df.agg({'产品名称':[max_count], '数量':['sum']})
# 使用 agg 方法对 DataFrame 进行聚合操作。在 agg 的参数中，字典的键是目标列名，而值是应用于该列的聚合函数。
# 在这里，'产品名称' 使用了自定义的 max_count 函数，而 '数量' 使用了内置的 sum 函数。

print(df1)

<class 'pandas.core.series.Series'>
                      产品名称    数量
销量个数最多的产品  蓝牙适配器     NaN
sum                        NaN  1097.0

### 通过字典或Series对象进行分组统计

In [16]:
import pandas as pd 

pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)

df = pd.read_excel('data/JD手机销售数据.xlsx')

print(df.head())
df=df.set_index('商品名称') # 设置商品名称为行索引
print('********************************************')

# 定义地区映射字典
dict1 = {
        '北京出库销量':'华北地区',
        '上海出库销量':'华东地区',
        '广州出库销量':'华南地区',
        '天津出库销量':'华北地区',
        '苏州出库销量':'华东地区',
        '沈阳出库销量':'东北地区',
        '杭州出库销量':'华东地区'
        }

df1 = df.groupby(dict1, axis=1).sum()
print(df1)

          商品名称  北京出库销量  上海出库销量  广州出库销量  天津出库销量  苏州出库销量  沈阳出库销量  杭州出库销量
0    荣耀V40轻奢版           747           666           578           284           246           156           152
1        OPPO A93            318           250           230           113            92            66            63
2  Apple iPhone 11           255           196           189           115            88            48            57
3        OPPO K7x            175           146           136            85            65            32            47
4       OPPO Reno5           149           100           115            82            63            37            40
********************************************
                 东北地区  华东地区  华北地区  华南地区
商品名称
荣耀V40轻奢版         156      1064      1031       578
OPPO A93               66       405       431       230
Apple iPhone 11        48       341       370       189
OPPO K7x               32       258       260       136
OPPO Reno5             37       203       231       115
Apple iPhone 12        34       163       148        88
荣耀X10                29       141       136        81
Redmi 9                13       122       137        75
Redmi K30S              9        62        83        51
OPPOA8                  5        79        66        42

C:\Users\Rainbow\AppData\Local\Temp\ipykernel_4180\1447442781.py:23: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df1 = df.groupby(dict1, axis=1).sum()

In [23]:
# 根据 Series对象进行分组

import pandas as pd 

pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)

df = pd.read_excel('data/JD手机销售数据.xlsx')

print(df.head())
df=df.set_index('商品名称') # 设置商品名称为行索引
print('********************************************')

dict1 = {
        '北京出库销量':'华北地区',
        '上海出库销量':'华东地区',
        '广州出库销量':'华南地区',
        '天津出库销量':'华北地区',
        '苏州出库销量':'华东地区',
        '沈阳出库销量':'东北地区',
        '杭州出库销量':'华东地区'
        }

s = pd.Series(dict1)    # 构建Series对象
print(s)
print('********************************************')
df2 = df.groupby(s, axis=1).sum()    # 分组， 按行统计求和
print(df2)

          商品名称  北京出库销量  上海出库销量  广州出库销量  天津出库销量  苏州出库销量  沈阳出库销量  杭州出库销量
0    荣耀V40轻奢版           747           666           578           284           246           156           152
1        OPPO A93            318           250           230           113            92            66            63
2  Apple iPhone 11           255           196           189           115            88            48            57
3        OPPO K7x            175           146           136            85            65            32            47
4       OPPO Reno5           149           100           115            82            63            37            40
********************************************
北京出库销量    华北地区
上海出库销量    华东地区
广州出库销量    华南地区
天津出库销量    华北地区
苏州出库销量    华东地区
沈阳出库销量    东北地区
杭州出库销量    华东地区
dtype: object
********************************************
                 东北地区  华东地区  华北地区  华南地区
商品名称
荣耀V40轻奢版         156      1064      1031       578
OPPO A93               66       405       431       230
Apple iPhone 11        48       341       370       189
OPPO K7x               32       258       260       136
OPPO Reno5             37       203       231       115
Apple iPhone 12        34       163       148        88
荣耀X10                29       141       136        81
Redmi 9                13       122       137        75
Redmi K30S              9        62        83        51
OPPOA8                  5        79        66        42

C:\Users\Rainbow\AppData\Local\Temp\ipykernel_4180\269708472.py:28: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df2 = df.groupby(s, axis=1).sum()    # 分组， 按行统计求和