### Missing value

In [1]:
import pandas as pd

pd.set_option('display.unicode.east_asian.width', True)
df = pd.read_excel('data/msb课程记录.xls')

print(df)

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12

In [2]:
# df.info() 用于打印 DataFrame 的简明摘要，包括有关其结构、数据类型、内存使用情况和非 null 值的信息。
print(df.info())
print('*'*80)

print(df.isnull())
print('*'*80)

print(df.notnull())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   买家会员名     11 non-null     object
 1   买家实际支付金额  11 non-null     float64
 2   课程总数量     9 non-null      float64
 3   课程标题      11 non-null     object
 4   类别        9 non-null      object
 5   订单付款时间    11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 656.0+ bytes
None
********************************************************************************
    买家会员名  买家实际支付金额  课程总数量  课程标题    类别  订单付款时间
0        False             False       False      False  False         False
1        False             False       False      False   True         False
2        False             False       False      False  False         False
3        False             False        True      False  False         False
4        False             False       False      False   True         False
5        False             False       False      False  False         False
6        False             False       False      False  False         False
7        False             False        True      False  False         False
8        False             False       False      False  False         False
9        False             False       False      False  False         False
10       False             False       False      False  False         False
********************************************************************************
    买家会员名  买家实际支付金额  课程总数量  课程标题    类别  订单付款时间
0         True              True        True       True   True          True
1         True              True        True       True  False          True
2         True              True        True       True   True          True
3         True              True       False       True   True          True
4         True              True        True       True  False          True
5         True              True        True       True   True          True
6         True              True        True       True   True          True
7         True              True       False       True   True          True
8         True              True        True       True   True          True
9         True              True        True       True   True          True
10        True              True        True       True   True          True

#### Handle Missing value

In [3]:
# method 1: delete missing value 
df = df.dropna()   # Delete all the rows which contains missing value
print(df)

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
2  2020-01-19 12:53:01
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12

In [4]:
import pandas as pd

pd.set_option('display.unicode.east_asian.width', True)
df = pd.read_excel('data/msb课程记录.xls')

print(df)
print('-'*50)

df = df[df['课程总数量'].notnull()]   # 提取 课程数量 中不为NaN的 record
print(df)

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12
--------------------------------------------------
   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12

In [5]:
# method 2: fill in with mean, median, mode

import pandas as pd

pd.set_option('display.unicode.east_asian.width', True)
df = pd.read_excel('data/msb课程记录.xls')

print(df)
print('-'*80)
df['课程总数量'] = df['课程总数量'].fillna(0)
# df['课程总数量'] = df['课程总数量'].fillna(df['课程总数量'].mean())
# df['课程总数量'] = df['课程总数量'].fillna(df['课程总数量'].median())
# df['课程总数量'] = df['课程总数量'].fillna(df['课程总数量'].mode())


print(df)

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12
--------------------------------------------------------------------------------
   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         0.0  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         0.0            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12

### Handle Repeating Value

In [8]:
import pandas as pd

pd.set_option('display.unicode.east_asian.width', True)
df = pd.read_excel('data/msb课程记录.xls')

print(df)
print('-'*50)

# 判断是否具有重复值
print(df.duplicated())
# print('-'*50)
# df=df.drop_duplicates(inplace=True)

# print(df)

print('-'*50)
# 删除指定列的重复数据, 保留重复行中的最后一行
# df = df.drop_duplicates(['买家实际支付金额'], keep='last')
# print(df)

# 直接删除，保留一个副本
df1 = df.drop_duplicates(subset=['买家实际支付金额'], inplace=False)
print(df1)

print('\nOriginal data: \n')
print(df)

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12
--------------------------------------------------
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool
--------------------------------------------------
  买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0     msb001          30960.00         2.0  Java互联网高级架构师  课程
1     msb002              1.00         1.0    金三银四面试突击班   NaN
2     msb003           9980.00         1.0    GoLang从入门到精通  课程
4     msb005              9.90         1.0       大前端VIP体验营   NaN
5     msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6     msb007           2400.00         1.0              操作系统  课程
8     msb009           2980.00         1.0        多线程与高并发  课程
9     msb010           1980.00         1.0              科技英语  课程

         订单付款时间
0 2020-10-09 22:54:26
1 2020-10-09 22:52:42
2 2020-01-19 12:53:01
4 2020-03-23 18:25:45
5 2020-03-24 19:25:45
6 2020-03-25 11:00:45
8 2020-03-27 07:25:30
9 2020-03-28 18:09:12

Original data:

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12

###  Detection and processing of outliers